Disable PostgreSQL setup in test workflow
Comment out PostgreSQL installation and database creation commands

diff --git a/.github/workflows/test-1.yml b/.github/workflows/test-1.yml
--- a/.github/workflows/test-1.yml
+++ b/.github/workflows/test-1.yml
@@ -12,10 +12,10 @@ jobs:
          echo $pwd
          docker --version
          ifconfig
-         sudo yum install -y postgresql15
-         export PGPASSWORD='.tqJ_Rf[?MXLGtyNURC8|sD<_dSd'
-         psql -h database-1.cnn3mmzdidcf.us-west-1.rds.amazonaws.com -U wei -d postgres -c "CREATE DATABASE mydb2;"
-         timeout 5 telnet database-1.cnn3mmzdidcf.us-west-1.rds.amazonaws.com 5432 2>&1 | grep -q "Connected" && echo "Connection successful" || echo "Connection failed"
+       #  sudo yum install -y postgresql15
+ #        export PGPASSWORD='.tqJ_Rf[?MXLGtyNURC8|sD<_dSd'
+  #       psql -h database-1.cnn3mmzdidcf.us-west-1.rds.amazonaws.com -U wei -d postgres -c "CREATE DATABASE mydb2;"
+    #     timeout 5 telnet database-1.cnn3mmzdidcf.us-west-1.rds.amazonaws.com 5432 2>&1 | grep -q "Connected" && echo "Connection successful" || echo "Connection failed"
 # cd /codebuild/output/src*/src/actions-runner
         # echo wei11
          # cd _diag
